# Use the official gcc image, based on debian.
# It can use version tags as well, like gcc:5.2.
# See https://hub.docker.com/_/gcc/ for more info.
image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive
build:
  stage: build
  before_script: 
    - apt-get update
    - apt-get -y install cmake freeglut3-dev git libarchive-dev libunshield-dev libxml2 libxml2-dev libzip-dev zlib1g-dev
    - git submodule update --init --recursive
  script:
    - rm ./pmdb/libstriezel/common/gui/glfw*
    - ./pmdb/ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
