language: cpp
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - git submodule update --init --recursive
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - freeglut3-dev
    - libglfw-dev
    - libxml2-dev
    - zlib1g-dev
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - ./pmdb/ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ..
  - make -j2
notifications:
  email: false
