language: cpp
compiler:
  - clang
  - gcc
# send to container-based infrastructure -> faster
sudo: false
before_install:
  - git submodule update --init --recursive
script:
  - mkdir ./build
  - cd ./build
  - cmake ..
  - make -j2
notifications:
  email: false
