language: cpp
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - git submodule update --init --recursive
addons:
  apt:
    packages:
    - freeglut3-dev
    - libglfw-dev
    - libxml2-dev
    - zlib1g-dev
script:
  - ./pmdb/ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ..
  - make -j2
notifications:
  email: false
