language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
    - master
    - travis
before_install:
  - git submodule update --init --recursive
script:
  - mkdir ./build
  - cd ./build
  - cmake ..
  - make
notifications:
  email: false
